const PREFIX = 'gema_'
const now = () => new Date().toISOString()
const id = (p) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
export const money = (value = 0) => `${new Intl.NumberFormat('fr-FR').format(value)} DA`
export const dateFr = (value) => value ? new Intl.DateTimeFormat('fr-FR').format(new Date(value)) : '—'

const brands = [
  ['Dell Latitude 5440', 'Ordinateur portable', 'Dell', '5440'], ['HP ProBook 450 G10', 'Ordinateur portable', 'HP', '450 G10'],
  ['Lenovo ThinkPad E14', 'Ordinateur portable', 'Lenovo', 'E14'], ['Écran Dell P2422H', 'Écran', 'Dell', 'P2422H'],
  ['Samsung Galaxy S24', 'Smartphone', 'Samsung', 'Galaxy S24'], ['iPhone 15', 'Smartphone', 'Apple', '15'],
  ['Imprimante HP LaserJet Pro', 'Imprimante', 'HP', 'M404dn'], ['Cisco Catalyst 9200', 'Équipement réseau', 'Cisco', 'C9200'],
  ['Serveur Dell PowerEdge T150', 'Serveur', 'Dell', 'T150'], ['Chaise ergonomique', 'Mobilier', 'Herman Miller', 'Sayl'],
  ['Canon imageFORMULA', 'Scanner', 'Canon', 'R40'], ['Tablette Samsung Galaxy Tab', 'Tablette', 'Samsung', 'S9'],
]
const people = [
 ['Yacine','Benali','Chef de projet','Informatique','Siège Alger'],['Amel','Boudiaf','Analyste RH','Ressources humaines','Siège Alger'],['Karim','Mansouri','Technicien réseau','Informatique','Agence Oran'],['Nadia','Zerrouki','Responsable commerciale','Commercial','Bureau Constantine'],['Sofiane','Belkacem','Comptable','Finance','Siège Alger'],['Lina','Khelifi','Chargée marketing','Marketing','Agence Oran'],['Mehdi','Saadi','Développeur','Informatique','Siège Alger'],['Sara','Boualem','Assistante direction','Direction','Siège Alger'],['Riad','Haddad','Logisticien','Logistique','Dépôt Sétif'],['Imane','Aït Ali','Acheteuse','Achats','Siège Alger'],['Walid','Gacem','Commercial','Commercial','Bureau Constantine'],['Samia','Bensaïd','Juriste','Juridique','Siège Alger'],['Anis','Brahimi','Technicien maintenance','Exploitation','Dépôt Sétif'],['Meriem','Kaci','Responsable RH','Ressources humaines','Siège Alger'],['Nabil','Djouadi','Administrateur systèmes','Informatique','Agence Oran'],['Yasmine','Lounis','Cheffe de produit','Marketing','Siège Alger'],['Hakim','Medjoub','Magasinier','Logistique','Dépôt Sétif'],['Nour','Benkaddour','Contrôleuse gestion','Finance','Bureau Constantine'],['Omar','Chibane','Responsable site','Direction','Agence Oran'],['Kenza','Hamel','Chargée recrutement','Ressources humaines','Siège Alger'],
]

function seed() {
 const employees = people.map(([first,last,job,department,site], i) => ({id:`emp-${i+1}`, matricule:`ATL-${String(i+1).padStart(4,'0')}`, firstName:first,lastName:last,email:`${first.toLowerCase()}.${last.toLowerCase().replaceAll(' ','')}@atlas-tech.dz`,phone:`055${String(1000000+i*731).slice(-7)}`,job,department,service:department,site,wilaya:site.includes('Oran')?'Oran':site.includes('Constantine')?'Constantine':site.includes('Sétif')?'Sétif':'Alger',hireDate:`202${i%4+1}-${String(i%9+1).padStart(2,'0')}-15`,exitDate:'',status:i===3?'Sortant':i===9?'En congé':i===16?'En période d’essai':'Actif',manager:i%3?'Meriem Kaci':'Omar Chibane',createdAt:now()}))
 const equipment = Array.from({length:40},(_,i)=>{const b=brands[i%brands.length]; const statuses=i===6||i===25?'En maintenance':i===18?'En attente de restitution':i===31?'Hors service':i<22?'Affecté':'Disponible'; return {id:`eq-${i+1}`,reference:`GEMA-MAT-2026-${String(i+1).padStart(4,'0')}`,designation:b[0],category:b[1],subCategory:b[1],brand:b[2],model:b[3],serial:`SN-AT${String(202600+i).padStart(6,'0')}`,inventory:`INV-ATL-${String(i+1).padStart(5,'0')}`,qr:`GEMA-MAT-2026-${String(i+1).padStart(4,'0')}`,status,condition:i===31?'Endommagé':i%9===0?'Bon état':'Très bon état',site:i%4===1?'Agence Oran':i%4===2?'Bureau Constantine':i%4===3?'Dépôt Sétif':'Siège Alger',location:i%4===3?'Magasin central':'Bureau '+(100+i),office:'',department:i%4===1?'Commercial':'Informatique',supplier:i%3===0?'Numidia IT Distribution':i%3===1?'Oran Digital Supply':'Atlas Bureau Services',acquisitionDate:`202${i%4+1}-0${i%9+1}-12`,serviceDate:`202${i%4+1}-0${i%9+1}-18`,price: 28000+(i%12)*23500,warrantyEnd:i%6===0?'2026-10-15':`202${7+i%2}-12-31`,depreciation:36,notes:'Donnée de démonstration – parc Atlas Technologies.',archived:false}})
 const active = equipment.filter(x=>x.status==='Affecté').map((e,i)=>({id:`aff-${i+1}`,reference:`GEMA-AFF-2026-${String(i+1).padStart(5,'0')}`,equipmentId:e.id,employeeId:employees[i%employees.length].id,date:`2026-0${i%8+1}-12`,reason:'Mise à disposition professionnelle',conditionOut:e.condition,accessories:'Chargeur, sacoche',site:e.site,location:e.location,comment:'Affectation validée.',manager:'Yacine Admin',status:'Affectée',createdAt:now()}))
 const history = Array.from({length:12},(_,i)=>({id:`aff-h-${i}`,reference:`GEMA-AFF-2025-${String(i+21).padStart(5,'0')}`,equipmentId:equipment[(i+24)%40].id,employeeId:employees[(i+5)%20].id,date:`2025-${String(i%9+1).padStart(2,'0')}-10`,reason:'Renouvellement de poste',conditionOut:'Bon état',accessories:'Chargeur',site:'Siège Alger',location:'Bureau 2'+i,comment:'Historique importé.',manager:'Gestionnaire du parc',status:'Restituée',createdAt:now()}))
 const maintenance = Array.from({length:10},(_,i)=>({id:`mnt-${i+1}`,reference:`GEMA-MNT-2026-${String(i+1).padStart(5,'0')}`,equipmentId:equipment[(i*3+2)%40].id,type:['Préventive','Corrective','Diagnostic','Réparation'][i%4],date:`2026-0${i%8+1}-0${i+4}`,provider:i%2?'Sarl Tech Services':'Numidia IT Distribution',cost:8500+i*2200,description:'Contrôle et intervention planifiés.',diagnostic:'Intervention de démonstration.',intervention:'Diagnostic effectué, matériel contrôlé.',nextMaintenance:'2027-02-15',status:i<2?'En cours':'Terminée',invoice:`FAC-2026-${100+i}`,createdAt:now()}))
 const users=[['Yacine','Admin','admin@gema.dz','Administrateur'],['Nadia','Parc','parc@gema.dz','Gestionnaire du parc'],['Meriem','Kaci','rh@gema.dz','Responsable RH'],['Omar','Chibane','site@gema.dz','Responsable de site'],['Yacine','Benali','employe@gema.dz','Collaborateur']].map((x,i)=>({id:`user-${i+1}`,firstName:x[0],lastName:x[1],email:x[2],phone:'0550 000 00'+i,job:i===0?'Directeur administratif':'Collaborateur',department:i===2?'Ressources humaines':'Informatique',site:i===3?'Agence Oran':'Siège Alger',role:x[3],status:'Actif',password:'demo123',createdAt:'2026-01-10',lastLogin:i?'2026-09-06T09:18:00':'2026-09-07T08:42:00'}))
 const suppliers=[['Numidia IT Distribution','Sofiane Nouri','021 55 12 10','contact@numidia-it.dz','Alger','Informatique & réseau'],['Oran Digital Supply','Leïla Kaci','041 32 70 22','ventes@orandigital.dz','Oran','Matériel informatique'],['Atlas Bureau Services','Karim Djelloul','021 48 60 11','contact@atlas-bureau.dz','Alger','Mobilier'],['Aurès Industrie','Amine Bensaïd','033 22 14 15','service@aures-industrie.dz','Batna','Équipement industriel'],['Horizon Distribution','Nora Belkacem','031 62 41 02','hello@horizon.dz','Constantine','Logistique'],['El Djazair Services','Riad Khelifi','021 45 01 31','contact@eldjazair.dz','Alger','Maintenance'],['Sétif Office Pro','Amel Aït Ali','036 71 80 04','contact@setifoffice.dz','Sétif','Fournitures'],['Béjaïa Secure','Samir Ouali','034 20 22 10','contact@bejaia-secure.dz','Béjaïa','Sécurité']].map((x,i)=>({id:`sup-${i+1}`,company:x[0],contact:x[1],phone:x[2],email:x[3],address:`Zone d’activité, ${x[4]}`,wilaya:x[4],rc:`RC-${i+1}A-16`,nif:`000${i+1}16000001`,specialty:x[5],notes:'Fournisseur de démonstration.'}))
 const sites=[['Siège Alger','12 rue Didouche Mourad, Alger','Alger','Yacine Admin'],['Agence Oran','18 boulevard Front de mer, Oran','Oran','Omar Chibane'],['Bureau Constantine','Cité administrative, Constantine','Constantine','Nadia Zerrouki'],['Dépôt Sétif','Zone industrielle El Eulma, Sétif','Sétif','Riad Haddad'],['Atelier Blida','Route de la Chiffa, Blida','Blida','Anis Brahimi']].map((x,i)=>({id:`site-${i+1}`,name:x[0],address:x[1],wilaya:x[2],manager:x[3],phone:`0${21+i} 00 00 0${i}`,departments:['Informatique','Commercial','Logistique']}))
 const categories=[...new Set(brands.map(x=>x[1])),'Téléphone','Véhicule','Outil','Équipement de sécurité','Caméra','Accessoire'].slice(0,12).map((name,i)=>({id:`cat-${i+1}`,name,description:'Référentiel du parc matériel'}))
 const documents=active.slice(0,8).map((a,i)=>({id:`doc-${i+1}`,reference:a.reference,type:i%2?'Bon de remise de matériel':'Attestation d’affectation de matériel',date:a.date,employeeId:a.employeeId,equipmentId:a.equipmentId,createdBy:'Yacine Admin',source:'affectation'}))
 const audit=Array.from({length:25},(_,i)=>({id:`log-${i+1}`,date:`2026-09-${String(7-i%6).padStart(2,'0')}T${String(8+i%9).padStart(2,'0')}:2${i%6}:00`,user:i%3?'Nadia Parc':'Yacine Admin',action:['Affectation créée','Matériel modifié','Maintenance enregistrée','Document généré','Collaborateur créé'][i%5],entity:i%2?'Parc matériel':'Gestion des collaborateurs',description:['Dell Latitude 5440 → Yacine Benali','Référence interne mise à jour','Intervention préventive enregistrée','GEMA-AFF-2026-00001 archivé','Nouveau profil créé'][i%5]}))
 return {company:{legalName:'ATLAS TECHNOLOGIES SARL',tradeName:'Atlas Technologies',address:'12 rue Didouche Mourad',wilaya:'Alger',commune:'Sidi M’Hamed',phone:'021 74 28 10',email:'contact@atlas-tech.dz',website:'www.atlas-tech.dz',nif:'001601234567890',rc:'16B0123456-00/16',nis:'001616012345678',ai:'1600123456',currency:'DA',adminManager:'Yacine Admin',assetManager:'Nadia Parc'},users,employees,equipment,assignments:[...active,...history],returns:[],maintenance,suppliers,sites,categories,kits:[{id:'kit-1',name:'Kit Poste de travail',items:['Ordinateur portable','Écran','Souris','Clavier','Casque'],notes:'Kit de référence pour les nouveaux collaborateurs.'}],documents,audit,notifications:[{id:'n1',type:'Garantie',message:'6 équipements arrivent en fin de garantie.',date:now(),read:false},{id:'n2',type:'Restitution',message:'Nadia Zerrouki est sortante : matériel à restituer.',date:now(),read:false},{id:'n3',type:'Maintenance',message:'2 interventions nécessitent un suivi.',date:now(),read:false}],counters:{AFF:active.length+13,RET:1,MNT:11,INV:1,TRF:1}}
}
const keys=['company','users','employees','equipment','assignments','returns','maintenance','suppliers','sites','categories','kits','documents','audit','notifications','counters']
export function bootstrap(){ const initial=seed(); keys.forEach(k=>{if(!localStorage.getItem(PREFIX+k)) localStorage.setItem(PREFIX+k,JSON.stringify(initial[k]))}); return readAll() }
export function readAll(){const fallback=seed(); return Object.fromEntries(keys.map(k=>[k,JSON.parse(localStorage.getItem(PREFIX+k)||JSON.stringify(fallback[k]))]))}
export function write(key,value){localStorage.setItem(PREFIX+key,JSON.stringify(value)); return readAll()}
export function reset(){keys.forEach(k=>localStorage.removeItem(PREFIX+k)); localStorage.removeItem('gema_session'); return bootstrap()}
export function add(key, record){const all=readAll(); const item={id:id(key.slice(0,3)),createdAt:now(),...record}; all[key]=[item,...all[key]]; return write(key,all[key])}
export function update(key,itemId,patch){const all=readAll(); all[key]=all[key].map(x=>x.id===itemId?{...x,...patch,updatedAt:now()}:x); return write(key,all[key])}
export function audit(user,action,entity,description){const all=readAll(); all.audit.unshift({id:id('log'),date:now(),user,action,entity,description}); return write('audit',all.audit)}
export function nextRef(type){const all=readAll(); const value=(all.counters[type]||1); all.counters[type]=value+1; write('counters',all.counters); return `GEMA-${type}-${new Date().getFullYear()}-${String(value).padStart(5,'0')}`}
export function addDocument(type,employeeId,equipmentId,user,source='manuel'){const all=readAll(); const code=source==='restitution'?'RET':source==='maintenance'?'MNT':'AFF'; const reference=nextRef(code); const doc={id:id('doc'),reference,type,date:new Date().toISOString().slice(0,10),employeeId,equipmentId,createdBy:user,source}; all.documents.unshift(doc); write('documents',all.documents); audit(user,'Document généré','Documents administratifs',reference); return doc}
export function assignEquipment(payload,user){const all=readAll(); const eq=all.equipment.find(x=>x.id===payload.equipmentId); if(!eq) throw new Error('Matériel introuvable.'); if(['Affecté','En maintenance','Hors service','Réformé'].includes(eq.status)) throw new Error(`Ce matériel est ${eq.status.toLowerCase()} et ne peut pas être affecté.`); const reference=nextRef('AFF'); const item={id:id('aff'),reference,date:new Date().toISOString().slice(0,10),status:'Affectée',conditionOut:eq.condition,accessories:'Chargeur',reason:'Mise à disposition professionnelle',manager:user,...payload,createdAt:now()}; all.assignments.unshift(item); all.equipment=all.equipment.map(x=>x.id===eq.id?{...x,status:'Affecté'}:x); write('assignments',all.assignments); write('equipment',all.equipment); const doc=addDocument('Attestation d’affectation de matériel',item.employeeId,item.equipmentId,user,'affectation'); audit(user,'Affectation créée','Affectations',`${eq.designation} → ${all.employees.find(x=>x.id===item.employeeId)?.firstName || ''} ${all.employees.find(x=>x.id===item.employeeId)?.lastName || ''}`); return {item,doc}}
export function returnEquipment(payload,user){const all=readAll(); const aff=all.assignments.find(x=>x.id===payload.assignmentId&&x.status==='Affectée'); if(!aff) throw new Error('Affectation active introuvable.'); const eq=all.equipment.find(x=>x.id===aff.equipmentId); const ret={id:id('ret'),reference:nextRef('RET'),date:new Date().toISOString().slice(0,10),status:'Validée',validatedBy:user,accessoriesReturned:'Chargeur',missingAccessories:'',damage:'',condition:'Bon état',...payload,equipmentId:aff.equipmentId,employeeId:aff.employeeId,createdAt:now()}; all.returns.unshift(ret); all.assignments=all.assignments.map(x=>x.id===aff.id?{...x,status:'Restituée',returnId:ret.id}:x); all.equipment=all.equipment.map(x=>x.id===eq.id?{...x,status:ret.condition==='Endommagé'?'En maintenance':'Disponible',condition:ret.condition}:x); write('returns',all.returns); write('assignments',all.assignments); write('equipment',all.equipment); addDocument('Procès-verbal de restitution de matériel',ret.employeeId,ret.equipmentId,user,'restitution'); audit(user,'Restitution validée','Restitutions',`${eq.designation} est disponible.`); return ret}
export function csvDownload(filename, rows){const data=rows.map(r=>Object.values(r).map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'); const blob=new Blob([data],{type:'text/csv;charset=utf-8;'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href)}